### ISSUE TITLE
baidu-aip-sdk/src/http/httpClientVoiceASR.js: Module crypto does not exist in the Haste module map

### ISSUE THREAD

**Issue by samuelltk** [Baidu-AIP/nodejs-sdk#10]
error: bundling failed: Error: Unable to resolve module `crypto` from `/Users/schneider/Documents/GitHub/Rock2/node_modules/baidu-aip-sdk/src/http/httpClientVoiceASR.js`: Module `crypto` does not exist in the Haste module map

SamuelMactekiMacBook-Pro:Rock SamuelMac$ react-native info

  React Native Environment Info:
    System:
      OS: macOS 10.14
      CPU: (8) x64 Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
      Memory: 1.09 GB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 10.13.0 - /usr/local/bin/node
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    IDEs:
      Xcode: 10.1/10B61 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.58.4 => 0.58.4 
    npmGlobalPackages:
      create-react-native-app: 2.0.2
      eslint-plugin-react-native: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7
      react-native-update-cli: 0.1.0

**Comment by samuelltk** [comment]
@chenxiaoyu3 @flyhighzy @PeterPanZH @meteorasd555 麻烦看一下，多谢。

**Comment by meteorasd555** [comment]
看起来是RN的import问题，可以参考RN的文档，或者这篇文章 https://www.jianshu.com/p/dee734041a90
