### ISSUE TITLE
【失望】demo缺乏

### ISSUE THREAD

**Issue by LaoCheng-cjs** [Baidu-AIP/nodejs-sdk#17]
> 我相信很多的东西手册写的不清不楚的，让别人怎么用，自己看着爽了。
```js
var HttpClient = require("baidu-aip-sdk").HttpClient;
 // 上面干嘛了这个，怎么关联上下面的。总之百度就是想累死人，直接说嘛，让我们直接提交问题，累死人
var client = new AipSpeechClient(APP_ID, API_KEY, SECRET_KEY);
```

**Comment by meteorasd555** [comment]
文档上写的还是比较清楚的，https://ai.baidu.com/ai-doc/SPEECH/Hk38lxkui
![image](https://user-images.githubusercontent.com/4214247/71543372-ac4c0b80-29ac-11ea-82cf-d50904ebdbde.png)
一个用来调用服务，一个用来设置全局http设置的
