### ISSUE TITLE
HttpClient, 在Linux系统报错

### ISSUE THREAD

**Issue by yuxichina** [Baidu-AIP/nodejs-sdk#2]
引入http模块时，大小写有误。Linux系统报错。

**Comment by xiewl** [comment]
我也出现这个问题了。
/node_modules/baidu-aip-sdk/src/AipOcr.js 第22行的大小写有误，导致Linux系统编辑报错
/node_modules/baidu-aip-sdk/src/AipNlp.js 第22行

**Comment by meteorasd555** [comment]
已经修复，npm也已经更新
