### ISSUE TITLE
一直返回3302错误

### ISSUE THREAD

**Issue by Sextants** [Baidu-AIP/nodejs-sdk#4]
var Client  = new AipSpeechClient(APPID, APIKey, SecretKey);

Client.authTypeReq().then(() => {
    let Voice   = FS.readFileSync('./16k3.pcm');
    
    let VoiceBuffer = new Buffer(Voice);
    
    Client.recognize(VoiceBuffer, 'pcm', 16000, {lan: 'zh', cuid: APPID}).then((result) => {
        console.log(JSON.stringify(result));
    }, (err) => {
        console.log(err);
    })
});

一直返回
{"err_msg":"authentication failed.","err_no":3302,"sn":"75241621661514821783"}

尝试修改AipSpeech.js文件的asrImpl方法，在85行增加requestInfo.makeDevOptions(this.devAccessToken);
可以通过验证；

recognize方法中Options的cuid应当填写APPID，否则返回参数错误，这个在文档中没有提。

**Comment by meteorasd555** [comment]
请确保你APPID, APIKey, SecretKey这三个参数填写正确，这些参数需要再百度云控制台里新建应用后查看应用详情获取

**Comment by meteorasd555** [comment]
gotDevAuthFail是内部方法无需手动调用，你只需要初始化的时候填对APPID, APIKey, SecretKey这三个参数后直接调用recognize这些接口就行了

**Comment by qiushijie** [comment]
我也遇到一样的问题，加入requestInfo.makeDevOptions(this.devAccessToken)后就行了

**Comment by Sextants** [comment]
个人理解，BaseClient的构造方法中最后一行this.authTypeReq();实际去调用了获取Token的接口，这个过程是一个异步过程，没有找到返回Promise对象或者传入CallBack的地方，目前试了两种方法，一种方式是设置setTimeout，延迟一段时间再调用识别的接口，另一种是调用authTypeReq在then中确认了请求完成token，然后再调用。

APPID, APIKey, SecretKey这个肯定填写正确，不然也不能提出尝试解决的办法。

**Comment by meteorasd555** [comment]
this.authTypeReq()会保存这个promise对象到this.pms这个变量的，asrImpl里调用doRequest方法里会用到这个this.pms的。
  @qiushijie @Sextants

**Comment by xiaoluoboding** [comment]
我也遇到同样的问题，官方示例的代码直接使用会出现3302错误，按 @Sextants 的说法改动之后会通过验证。

**Comment by meteorasd555** [comment]
asrImpl(param) {
        let httpClient = new HttpClientVoiceASR();
        let requestInfo = new RequestInfo(PATH_VOP, param, METHOD_POST, false, {
                [httpHeader.CONTENT_TYPE]: CONTENT_TYPE_JSON
            });
        requestInfo.setHost(HOST_VOP);
        return this.doRequest(requestInfo, httpClient);
85行在这里，这里加入requestInfo.makeDevOptions(this.devAccessToken)这句？
    }
你们难道是这样改的？85行这代码也不会执行吧

**Comment by meteorasd555** [comment]
这边排查出了可能的原因，是因为你们的应用都是在speech.baidu.com创建的而不是bce.baidu.com,SDK这块的逻辑没有兼容，后续版本会兼容这些应用，推荐你们去bce.baidu.com新建语音的应用。

**Comment by XianglongLu** [comment]
我的应用也是之前建立的。
使用python sdk没问题，但使用nodejs就有问题（error 3302）。
按照@meteorasd555 说的新建一个应用，nodejs已可以正常使用。

**Comment by meteorasd555** [comment]
已修复于2.1.0
