### ISSUE TITLE
跨域

### ISSUE THREAD

**Issue by tangmingming** [Baidu-AIP/nodejs-sdk#5]
我想用在前端   请问有什么办法搞定跨域请求？

**Comment by PeterPanZH** [comment]
两个方面
第一，nodejs SDK 目前不能直接用在浏览器环境里，如果想从前端直接调用需要自己写
第二，关于跨域，目前有部分 API 已经支持 CORS，其他接口也正在逐步增加中。但是，获取 access_token 的接口是**不打算**支持 CORS 的，因为将 AK/SK 直接写在 client 端是具有极高风险的，我们不建议开发者这么做。
目前怎么做？建议通过自己的服务器来中转。目前所有的请求都通过服务器中转比较靠谱，今后可能只需要获取 access_token 这一步需要通过自己的鉴权服务器去通信。另外以后直接能用在浏览器端的 js SDK 也会有（当然还是需要一个自己的鉴权服务器）。
