### ISSUE TITLE
failed to find cluster with per and lan.

### ISSUE THREAD

**Issue by mahmoudfelfel** [Baidu-AIP/nodejs-sdk#7]
The documentation mentions the availability of English voices, and female and male persons, but whenever I try to pass anything for the option `per` other than 0 for language `en` I get this error:
```
{ err_detail: 'failed to find cluster with per and lan.',
  err_msg: 'parameter error.',
  err_no: 501,
  err_subcode: 22,
  tts_logid: 393635243 }
```
Is the only voice available for English is a female voice?

**Comment by meteorasd555** [comment]
the  option **lan** only can be set to "zh" , supports both English and Chinese Automatically. You can see doc at http://ai.baidu.com/docs#/TTS-API/top
