### ISSUE TITLE
Speech 接口超时时间太短

### ISSUE THREAD

**Issue by 599316527** [Baidu-AIP/nodejs-sdk#8]
默认的 10s 超时对于语音识别接口来说有点短，目前的实现感觉改这个超时不太好改。直接覆盖 `require('xxxx').HttpClient.DEFAULT_TIMEOUT= 1e5` 不太优雅，又没有通过参数传 timeout 进去的方式。改成 `requestInfo.timeout || HttpClient.DEFAULT_TIMEOUT` 更好？

https://github.com/Baidu-AIP/nodejs-sdk/blob/d9febf54b20d29df40916adf123adc707a13ab5c/src/http/httpClient.js#L94

https://github.com/Baidu-AIP/nodejs-sdk/blob/d9febf54b20d29df40916adf123adc707a13ab5c/src/http/httpClientVoiceASR.js#L43-L52

**Comment by meteorasd555** [comment]
var HttpClient = require("baidu-aip-sdk").HttpClient;

// 设置request库的一些参数，例如代理服务地址，超时时间等
// request参数请参考 https://github.com/request/request#requestoptions-callback
HttpClient.setRequestOptions({timeout: 5000});

// 也可以设置拦截每次请求（设置拦截后，调用的setRequestOptions设置的参数将不生效）,
// 可以按需修改request参数（无论是否修改，必须返回函数调用参数）
// request参数请参考 https://github.com/request/request#requestoptions-callback
HttpClient.setRequestInterceptor(function(requestOptions) {
    // 查看参数
    console.log(requestOptions)
    // 修改参数
    requestOptions.timeout = 5000;
    // 返回参数
    return requestOptions;
});

**Comment by 599316527** [comment]
原来如此
